CREATE TABLE PESSOA(
	CODIGO BIGINT NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	ATIVO BOOLEAN NOT NULL,
	LOGRADOURO VARCHAR(50), 
	NUMERO VARCHAR(30),
	COMPLEMENTO VARCHAR(200),
	BAIRRO VARCHAR(80),
	CEP VARCHAR(20),
	CIDADE VARCHAR(200),
	ESTADO VARCHAR(100)
);

CREATE SEQUENCE PESSOA_CODIGO
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

ALTER TABLE PESSOA ALTER COLUMN CODIGO SET DEFAULT NEXTVAL('PESSOA_CODIGO' :: regclass);

INSERT INTO PESSOA(NOME, ATIVO) VALUES ('João Pedro', true);
INSERT INTO PESSOA(NOME, ATIVO) VALUES ('Maria Beatriz', true);
INSERT INTO PESSOA(NOME, ATIVO) VALUES ('Evaldo José', true);
INSERT INTO PESSOA(NOME, ATIVO) VALUES ('José Vitor', false);
INSERT INTO PESSOA(NOME, ATIVO) VALUES ('Nathália', true);
INSERT INTO PESSOA(NOME, ATIVO) VALUES ('Samuel José', false);
INSERT INTO PESSOA(NOME, ATIVO) VALUES ('Maria Clara', false);
INSERT INTO PESSOA(NOME, ATIVO) VALUES ('Catharina Gianna', true);
INSERT INTO PESSOA(NOME, ATIVO) VALUES ('Lorenzo Augusto', true);
INSERT INTO PESSOA(NOME, ATIVO) VALUES ('Aniê Perfeita', true);
